### ISSUE TITLE
Allow for complete Durable Sync engine testing against staging 

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/services-engineering#29]
This is a [Q1 2020 Goal for the SE Team](https://docs.google.com/spreadsheets/d/1RjDzgs-CMuqRD5K18SbkD__RwgBiDcgmLiCqjwTbjOU/edit#gid=21744728).

Linking all related issues to the efforts to more fully test Sync against staging for all Sync clients.

# Related issues:
* [x] [move existing sync setup docs to dochub](https://github.com/mozilla-services/services-engineering/issues/25).

# Missing functionality:
* [x] Fenix support. Tracking epic for this work is [here](https://jira.mozilla.com/browse/SYNC-926)

* [ ] [Lockwise Android Support](https://github.com/mozilla-lockwise/lockwise-android/issues/1129) - won't make it into Q1 for lockwise team.
* [ ] [Lockwise iOS Support](https://github.com/mozilla-lockwise/lockwise-android/issues/1129) - won't make it into Q1 for lockwise team.
