### ISSUE TITLE
2020-Q1 Rust dependency update

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/services-engineering#30]
Update the various libraries and dependencies for:

- [x] [autopush](https://github.com/mozilla-services/autopush/) https://github.com/mozilla-services/autopush/pull/1359
- [ ] [autopush-rs](https://github.com/mozilla-services/autopush-rs/)
- [x] [channelserver](https://github.com/mozilla-services/channelserver)
- [x] [fernet-rs](https://github.com/mozilla-services/fernet-rs)
- [x] [megaphone](https://github.com/mozilla-services/megaphone)
- [x] mozilla-rust-sdk
- [x] [pushbox](https://github.com/mozilla-services/pushbox/)
- [x] ~~[syncstorage-loadtest](https://github.com/mozilla-services/syncstorage-loadtest)~~ (Skip for now, it doesn't pin versions)
- [ ] [syncstorage-rs](https://github.com/mozilla-services/syncstorage-rs)
