### ISSUE TITLE
[meta] sync quota tracking bug

### ISSUE THREAD

**Issue by tublitzed** [mozilla-services/services-engineering#41]
Spanner has a [limitation](https://cloud.google.com/spanner/quotas) on how much data we can store per user collection. We need to find a way to move forward with the migration in a way that doesn't negatively impact spanner.

Affected users tracked in [1653022](https://bugzilla.mozilla.org/show_bug.cgi?id=1653022)

This will track:
* [x] Determining preferred approach. [Plan is here](https://docs.google.com/document/d/1-vE423-65KlnAWWDH5yqhVE-Tr0eV-iVh_qrsJmAyRE/edit#)
* [ ] Getting it implemented/released:
   * ~[ ] client side changes - [1655531](https://bugzilla.mozilla.org/show_bug.cgi?id=1655531)~
   * [x] test to confirm clients work as expected already - [1655531](https://bugzilla.mozilla.org/show_bug.cgi?id=1655531)
   * [x] server side changes - https://github.com/mozilla-services/syncstorage-rs/issues/746
   * [x] testing to confirm server side changes work as expected. - https://jira.mozilla.com/browse/PI-773
   * [x] doc changes - https://github.com/mozilla-services/docs/issues/85
   * [x] Isolate existing affected legacy sync users pre-migration [1658399](https://bugzilla.mozilla.org/show_bug.cgi?id=1658399)
   * [x] notify SUMO (started slack thread [here](https://mozilla.slack.com/archives/C011FHVHUG7/p1597089283103900))
   * [ ] Deprecate POST "failed" bsos https://github.com/mozilla-services/syncstorage-rs/issues/418 (See [below](https://github.com/mozilla-services/services-engineering/issues/41#issuecomment-703010374) for why this is needed)

**Comment by erkolson** [comment]
While testing whole node migrations of user data from sync-py to sync-rs, I've discovered some users take an exceptionally long time to migrate (2+ hours).  I ran some queries to create a distribution of rows and users.  I found that though the 99th percentile user on this particular node had ~110,000 rows, the 3 biggest users had more than 9 million rows.

#### Migration time:
1.  mean user - ~4s
1.  99th percentile user - 0:01:40 (100s)
1.  9,000,000 row user - 2:06:21 (8181s)

There are many processes working in parallel to transfer the data but these extreme outlier users make it very difficult to create optimal workload allocations for parallel processes.  i.e. If we have enough processes to migrate the entire node in 2.5 hours based on total rows, average throughput, and an even allotment of users across all processes -- the presence of one of these users in a process's allocation will cause it to take closer to 5 hours.

**Comment by davismtl** [comment]
Some food for thought as we work on a policy. We should align with client-side integration since it doesn't sync all the data on a first sync. So if we decide to keep 1 year of data or 100k records, it doesn't mean that the client will ever use it.

**Comment by tublitzed** [comment]
I'm going to pick this one back up in light of the recently discovered spanner limitation. Update to come after reviewing options with product.

**Comment by tublitzed** [comment]
Adjusting the scope of this ticket to specifically track handling the spanner limitation.

**Comment by jrconlin** [comment]
from rbillings [load test](https://mozilla.slack.com/archives/CKL0LGV9B/p1600973504004800):

```
11:51 AM
rbillings @jrconlin results: SUCCESSES: 1027241 | FAILURES: 252 | WORKERS: 800
```

This was with 0.6.0 with quota disabled.

**Comment by jrconlin** [comment]
~Unfortunately, rbillings will be out tomorrow and ops is currently dealing with a higher priority issue, so load testing 0.6.0 with quota enabled will have to wait for Monday, Sept 28.~

**Comment by jrconlin** [comment]
Ops was able to enable quota on storage. Load testing results:
```
3:35 PM rbillings SUCCESSES: 1027815 | FAILURES: 132 | WORKERS: 800 looks good!
```
Which is inline with the prior results. 

She noticed no timing differences with the quota enabled.

**Comment by pjenvey** [comment]
I'm seeing a probably unexpected failure case of the quota check from Vasilica's latest log:

https://bugzilla.mozilla.org/show_bug.cgi?id=1665917#c4

After a "successful" batch commit the sync client reports:

```
601543067675	Sync.Collection	DEBUG	POST success 200 https://stage.sync.nonprod.cloudops.mozgcp.net/1.5/<id>/storage/bookmarks?batch=<batch_id>commit=true
1601543067676	Sync.Engine.Bookmarks	DEBUG	Records that will be uploaded again because the server couldn't store them: <bso_id>, <etc>
```

Looking at the Sync client, "Records that will be uploaded again because the server couldn't store them" seem to indicate the write was successful but included "failed" bsos.

I believe the "failed" bucket was populated here due to the quota check failing in batch append (or post_bsos). When this happens there's no indication to the client that the quota check failed (the "failed" bucket does include an error message, so the quota error might be included there but it's likely ignored), which I'd consider a bug.

We've already [planned to deprecate populating of this "failed" bucket feature entirely](https://github.com/mozilla-services/syncstorage-rs/issues/418) -- I think we likely need to remove it now to fix this issue (I've added it to the checklist)

**Comment by mhammond** [comment]
While this isn't ideal, it's probably not too much of a problem TBH - the next sync will explicitly retry those failed items once. However, if it's failing due to the quota, then the clients are forever going to retry anyway. The only "bad" thing happening here that wouldn't if this was fixed is that Firefox will write a json file with the failed guids.
